version: '3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    environment:
      - IP=0.0.0.0
      - PORT=9080
      - DB_HOST=172.17.0.1 # type 'ip a | grep docker', get this IP 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=gfgtutor
      - DB_SSL_MODE=disable
    ports:
      - "9080:9080" # проброс порта 9080 на хост-машину